### ISSUE TITLE
Redirection to changed URLs in MultisitesFrontController

### ISSUE THREAD

**Issue by tardinha** [symbiote/silverstripe-multisites#34]
Hi,

Redirects to changed URLs are failing due to an undefined variable ( `$URL` ) on [line 56](https://github.com/sheadawson/silverstripe-multisites/blob/master/code/controllers/MultisitesFrontController.php#L56):

``` php
$redirect = SiteTree::get_by_link($url);
```

Cheers

Mark

**Comment by nglasl** [comment]
Closing since this has been resolved.
