### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by silbinarywolf** [symbiote/silverstripe-multisites#88]
Failing build:
https://travis-ci.org/symbiote/silverstripe-multisites/jobs/371400716

Information:
```
..F                                                                 3 / 3 (100%)
Time: 6 seconds, Memory: 78.00MB
There was 1 failure:
1) Symbiote\Multisites\Tests\MultisiteSiteTest::testRequestSecondPage
Failed asserting that 404 matches expected 200.
/home/travis/build/symbiote/silverstripe-multisites/tests/MultisiteSiteTest.php:112
/home/travis/build/symbiote/silverstripe-multisites/vendor/phpunit/phpunit/phpunit:52
FAILURES!
Tests: 3, Assertions: 3, Failures: 1.
```

**Comment by nglasl** [comment]
@silbinarywolf assigning this one to you since you were already looking at failing builds. Please let me know if there's anything I can help with here.

**Comment by nglasl** [comment]
Closing this one as tests are temporarily disabled for now, and will be enabled again soon (now that the master branch for each module is protected :hands:). If tests are still failing when that happens, I'll either create a new issue or personally resolve them.
