### ISSUE TITLE
Error pages created based on current site url (not multisites aware)

### ISSUE THREAD

**Issue by stephenmcm** [symbiote/silverstripe-multisites#89]
When ErrorPage generates the static version of the page it does:
```php
$response = Member::actAs(null, function () {
    return Director::test(Director::makeRelative($this->Link()));
});
```
While the `$this->link()` will return the correct (full) url, Director::makeRelative() then rewrites it to the current site url regardless of the Pages parent site.
The fix for this is likely creating a multi-sites error page that checks it's site context.

**Comment by nglasl** [comment]
Can you please provide the affected SS version/s?

**Comment by stephenmcm** [comment]
I was testing against SilverStripe 4.x but I'd guess SilverStripe 3.x has the same issue.

**Comment by nglasl** [comment]
Thanks @stephenmcm!

**Comment by nglasl** [comment]
Assigning this one back to you @stephenmcm as per IRL discussions. Please give me an update on this one when you can.

**Comment by nglasl** [comment]
Assigning this one back to you @stephenmcm as per IRL discussions. Please let me know if there's anything I can do to help.

**Comment by nglasl** [comment]
With https://github.com/symbiote/silverstripe-multisites/pull/91 currently open and in review, I'm going to close this issue so we have a single thread for discussion and resolution.
