### ISSUE TITLE
Missing namespaces causes fatal error

### ISSUE THREAD

**Issue by Andrew-Mc-Cormack** [symbiote/silverstripe-multisites#92]
In silverstripe-multisites/src/Admin/MultisitesModelAdminExtension.php

The following 2 namespaces are required:

use Symbiote\Multisites\Multisites;
use Symbiote\Multisites\Model\Site;

**Comment by nglasl** [comment]
I'll look at adding these, seems like a simple fix.

**Comment by nglasl** [comment]
@Andrew-Mc-Cormack this is now fixed. I was also seeing a maximum nesting issue when testing this locally, but I feel like that's related to my development environment so it's probably safe to ignore for now.
