### ISSUE TITLE
SS 4.3 breaks MultisitesModelAdminExtension

### ISSUE THREAD

**Issue by JoshuaCarter** [symbiote/silverstripe-multisites#96]
#### Issue

https://github.com/symbiote/silverstripe-multisites/blob/master/src/Admin/MultisitesModelAdminExtension.php#L175-L178

Changes make to `ModelAdmin.php` in SS 4.3 (roughly [here](https://github.com/silverstripe/silverstripe-admin/blob/4f68e4b759c104b2690050af034a41d370d2e6e4/code/ModelAdmin.php#L265-L279)) cause infinite recursion with `MultisitesModelAdminExtension.php`.

The resulting call stack looks something like:

```
1.  MultisitesModelAdminExtension::onAfterInit()
2.  MultisitesModelAdminExtension::modelIsMultiSitesAware()
3.  MultisitesModelAdminExtension::getListDataClass()
4.  ModelAdmin::getSearchContext()
5.  ModelAdmin::getEditForm()
6.  ModelAdmin::getList()
7.  MultisitesModelAdminExtension::updateList()
8.  MultisitesModelAdminExtension::modelIsMultiSitesAware()
// repeat 3-8 forever
```

The changes to `ModelAdmin` are such that:
- No aparent way to the get the `dataClass` being managed by the extension's `owner`.
- No aparent way to get a `DataList` of results without also triggering the extension.

The closest I got was replacing `MultisitesModelAdminExtension::getListDataClass()` with:
```
private function getListDataClass() {
    if(!$this->listDataClass) {
        $models = $this->owner->getManagedModels();
        $class = key($models); //assumes only one model managed
        $this->listDataClass = singleton($class);
    }
    return $this->listDataClass;
}
```
But this falls flat by assuming that there's only one managed model (where there may be several).

#### Proposed Solution 1 

The purpose of `MultisitesModelAdminExtension` is to handle object with the `MultisitesAware` extension. It has been suggested (internally) that this is an old workaround that may no longer be relevant.

We should look into whether any project are using `MultisitesAware` and if not (or sufficiently few/outdated projects), then perhaps this aspect of the module can be removed entirely.

#### Proposed Solution 2 

If it turns out we *do* need this functionality, then a PR on `silverstripe-admin` to expose `ModelAdmin::$modelClass` would allow an easy fix on our end.

**Comment by JoshuaCarter** [comment]
PR in progress: https://github.com/silverstripe/silverstripe-admin/pull/813

**Comment by JoshuaCarter** [comment]
Upstream change complete (which enables a fix here) but wont be present until 1.4 of silverstripe-admin.

@nglasl Thoughts on whether to wait for 1.4 or take another approach? Doubt we can require a commit/branch due to the way ss-recipe works etc?

**Comment by robbieaverill** [comment]
Would adding the public getter with an extension in your project code (to ModelAdmin) effectively work as a temporary replacement?

**Comment by nglasl** [comment]
@JoshuaCarter looking at the CMS requirements, I believe you should be able to pull the latest 1.X commit down https://github.com/silverstripe/silverstripe-cms/blob/4/composer.json#L22 depending on the project and whether you're using a specific recipe version. I'd be inclined to enforce this from the `composer.json`, but as above, this won't always work if somebody is using a specific recipe version.

So yeah, we can either include this change using an extension for now as @robbieaverill suggested, or we can look towards deprecating the extension (I only raise this because I recall the extension being a work around to achieve the same result as https://github.com/silverstripe/silverstripe-subsites, in which case, perhaps it's better to use that module where it makes sense).

**Comment by JoshuaCarter** [comment]
@robbieaverill You bloody beaut 👍

**Comment by mrvickiee** [comment]
Hi, any update on the fix ? Thanks.

**Comment by JoshuaCarter** [comment]
@nglasl PR here : https://github.com/symbiote/silverstripe-multisites/pull/97

Need to discuss how this will impact the module version and/or whether there's any decent way to retain backwards compatibility (the main issue being that the old method hangs which makes it hard to `try` etc).

**Comment by nglasl** [comment]
Thanks @JoshuaCarter, have left some review comments. @mrvickiee just a heads up that I'm going to close this issue and we'll move any further discussion and progress updates over to the PR above (so we have a single point of discussion).
